#! /bin/sh
rm -f config.log config.status confdehs.h *.gcno \
       src/*.o src/*.so src/Makevars src/symbols.rds \
       *~ */*~
make -C src/scs/build clean
rm -rf src/scs/build
rm -rf autom4te.cache
for f in ./config.*; do
rm -f $f
done
exit 0
