# Generated by packamon: do not edit by hand
# Instead of modifying this file, you can modify a template. See ?init for details.

FROM registry.openanalytics.eu/openanalytics/r-ver-tools:4.6.1

LABEL maintainer="joris.chau@openanalytics.eu"

ARG PKGNAME="cvxoptdes"
ENV PKGNAME=${PKGNAME}

##include packamon.system-dependencies

# System libraries (incl. system requirements for R packages)
RUN apt-get update && apt-get install --no-install-recommends -y \
    libcurl4-openssl-dev \
    libicu-dev \
    libssl-dev \
    libxml2-dev \
    make \
	cmake \
    pandoc \
    && rm -rf /var/lib/apt/lists/*

RUN echo \
    'options(repos = c(CRAN = gsub("/([0-9-]*)$", "/latest", Sys.getenv("CRAN", "https://cloud.r-project.org")), CRAN.source = "https://cloud.r-project.org"))' \
    >> $(R RHOME)/etc/Rprofile.site

# install dependencies
RUN R -q -e "options(warn = 2); \
    install.packages('remotes'); \
    remotes::install_version('backports', version = '1.5.1', upgrade = FALSE); \
    remotes::install_version('base64enc', version = '0.1-6', upgrade = FALSE); \
    remotes::install_version('cli', version = '3.6.6', upgrade = FALSE); \
    remotes::install_version('crayon', version = '1.5.3', upgrade = FALSE); \
    remotes::install_version('digest', version = '0.6.39', upgrade = FALSE); \
    remotes::install_version('evaluate', version = '1.0.5', upgrade = FALSE); \
    remotes::install_version('fastmap', version = '1.2.0', upgrade = FALSE); \
    remotes::install_version('fs', version = '2.1.0', upgrade = FALSE); \
    remotes::install_version('glue', version = '1.8.1', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('jsonlite', version = '2.0.0', upgrade = FALSE); \
    remotes::install_version('lattice', version = '0.22-9', upgrade = FALSE); \
    remotes::install_version('mime', version = '0.13', upgrade = FALSE); \
    remotes::install_version('nanonext', version = '1.10.1', upgrade = FALSE); \
    remotes::install_version('pkgconfig', version = '2.0.3', upgrade = FALSE); \
    remotes::install_version('prettyunits', version = '1.2.0', upgrade = FALSE); \
    remotes::install_version('R6', version = '2.6.1', upgrade = FALSE); \
    remotes::install_version('rappdirs', version = '0.3.4', upgrade = FALSE); \
    remotes::install_version('rbibutils', version = '2.4.1', upgrade = FALSE); \
    remotes::install_version('Rcpp', version = '1.1.2', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('rlang', version = '1.3.0', upgrade = FALSE); \
    remotes::install_version('xfun', version = '0.60', upgrade = FALSE); \
    remotes::install_version('yaml', version = '2.3.12', upgrade = FALSE); \
    remotes::install_version('cachem', version = '1.1.0', upgrade = FALSE); \
    remotes::install_version('checkmate', version = '2.3.4', upgrade = FALSE); \
    remotes::install_version('highr', version = '0.12', upgrade = FALSE); \
    remotes::install_version('htmltools', version = '0.5.9', upgrade = FALSE); \
    remotes::install_version('lifecycle', version = '1.0.5', upgrade = FALSE); \
    remotes::install_version('Matrix', version = '1.7-6', upgrade = FALSE); \
    remotes::install_version('mirai', version = '2.7.2', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('nlme', version = '3.1-170', upgrade = FALSE); \
    remotes::install_version('Rdpack', version = '2.6.6', upgrade = FALSE); \
    remotes::install_version('tinytex', version = '0.60', upgrade = FALSE); \
    remotes::install_version('fontawesome', version = '0.5.3', upgrade = FALSE); \
    remotes::install_version('highs', version = '1.14.0-2', upgrade = FALSE); \
    remotes::install_version('jquerylib', version = '0.1.4', upgrade = FALSE); \
    remotes::install_version('knitr', version = '1.51', upgrade = FALSE); \
    remotes::install_version('memoise', version = '2.0.1', upgrade = FALSE); \
    remotes::install_version('mgcv', version = '1.9-4', upgrade = FALSE); \
    remotes::install_version('reformulas', version = '0.4.4', upgrade = FALSE)"
RUN R -q -e "options(warn = 2); \
    remotes::install_version('sass', version = '0.4.10', upgrade = FALSE); \
    remotes::install_version('vctrs', version = '0.7.3', upgrade = FALSE); \
    remotes::install_version('bslib', version = '0.11.0', upgrade = FALSE); \
    remotes::install_version('hms', version = '1.1.4', upgrade = FALSE); \
    remotes::install_version('progress', version = '1.2.3', upgrade = FALSE); \
    remotes::install_version('rmarkdown', version = '2.31', upgrade = FALSE); \
    if (!requireNamespace('roxygen2', quietly = TRUE)) install.packages('roxygen2'); \
    if (!requireNamespace('covr', quietly = TRUE)) install.packages('covr')"

RUN R -q -e "options(warn = 2); \
    install.packages('checkglobals')"

##include packamon.local-r-dependencies

##include packamon.runtime-settings

## install local package(s)
RUN mkdir -p /tmp
WORKDIR /tmp
COPY . /tmp/${PKGNAME}
RUN R -q -e "install.packages(pkgbuild::build('${PKGNAME}'), repos = NULL, dependencies = FALSE)"
